# Generated by Django 3.2.12 on 2022-03-29 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_item_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
    ]
