# Generated by Django 3.2.12 on 2022-06-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20220623_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='set_defaults',
            field=models.BooleanField(default=False),
        ),
    ]
