# Generated by Django 3.2.12 on 2022-06-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_item_set_defaults'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='set_defaults',
            new_name='update_defaults',
        ),
    ]
