# Generated by Django 3.2.12 on 2022-06-24 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_set_defaults_item_update_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='item',
        ),
        migrations.AddField(
            model_name='variation',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
    ]
