# Generated by Django 3.2.12 on 2022-05-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20220511_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingmessage',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='marketingmessage',
            old_name='startdate',
            new_name='start_date',
        ),
    ]
