# Generated by Django 3.2.12 on 2022-05-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20220511_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingmessage',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingmessage',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
