# Generated by Django 3.2.12 on 2022-05-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_auto_20220515_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
