# Generated by Django 3.2.12 on 2022-05-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailmarketingsignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmarketingsignup',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailmarketingsignup',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
