# Generated by Django 3.2.12 on 2022-04-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20220409_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_item',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_items',
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='cart.CartItem'),
        ),
    ]
