# Generated by Django 3.2.12 on 2022-04-09 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20220409_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='cart_items',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='item',
            new_name='cart_item',
        ),
    ]
