# Generated by Django 3.2.12 on 2022-04-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_item_size'),
        ('cart', '0008_auto_20220409_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='store.Item'),
        ),
    ]
