# Generated by Django 3.2.12 on 2022-04-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20220411_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=100),
        ),
    ]
