# Generated by Django 3.2.12 on 2022-06-20 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_useraddress_options'),
        ('orders', '0007_auto_20220620_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_biling',
            field=models.ForeignKey(blank=True, default=55, max_length=350, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_billing', to='accounts.useraddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_shipping',
            field=models.ForeignKey(blank=True, default=55, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_shipping', to='accounts.useraddress'),
        ),
    ]
